pluginManagement {
  repositories {
    maven {
      url = new File(rootDir.parentFile.parentFile.parentFile.parentFile, "build/localMaven")
    }
    mavenCentral()
    google()
  }
}

dependencyResolutionManagement {
  versionCatalogs.register("libs") {
    from(files("../../../../gradle/libs.versions.toml"))

    // This version is set in the GradleRunner during test setup using the current (SNAPSHOT) version.
    // If you want to use the test projects as standalone samples, link the Gradle project in IntelliJ
    // and overwrite this version.
    plugin("licensee", "app.cash.licensee").version(licenseeVersion)
  }

  repositories {
    maven {
      url = new File(rootDir.absoluteFile, "repo")
    }
    mavenCentral()
    google()
  }
}
